### ISSUE TITLE
geovista.pantry.meshes are broken

### ISSUE THREAD

**Issue by bjlittle** [bjlittle/geovista#672]
## 🐛 Bug Report

```
> python -c "from geovista.pantry.meshes import dynamico; print(dynamico())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/net/home/h05/itwl/projects/git/geovista/src/geovista/pantry/meshes.py", line 171, in dynamico
    sample = geovista.pantry.data.dynamico()
             ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'geovista.pantry' has no attribute 'data'
```

Introduced by https://github.com/bjlittle/geovista/pull/645.

## Expected Behaviour

```
> python -c "from geovista.pantry.meshes import dynamico; print(dynamico())"
PolyData (0x7ff598f29720)
  N Cells:    16002
  N Points:   96012
  N Strips:   0
  X Bounds:   -1.000e+00, 1.000e+00
  Y Bounds:   -9.998e-01, 9.998e-01
  Z Bounds:   -9.999e-01, 9.999e-01
  N Arrays:   4
```

## Environment

```
----------------------------------------------------------------------------------------
  Date: Fri Jan 26 01:29:00 2024 GMT

                  OS : Linux
              CPU(s) : 4
             Machine : x86_64
        Architecture : 64bit
         Environment : Python
          GPU Vendor : VMware, Inc.
        GPU Renderer : llvmpipe (LLVM 7.0, 256 bits)
         GPU Version : 3.3 (Core Profile) Mesa 18.3.4

  Python 3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 08:03:24) [GCC 12.3.0]

             cartopy : 0.22.0
               click : 8.1.7
 click-default-group : 1.2.4
             cmocean : 3.0.3
            colorcet : 3.0.1
            geovista : 0.5.0.dev169
          matplotlib : 3.8.2
             netcdf4 : 1.6.5
               numpy : 1.26.3
        platformdirs : 4.1.0
               pooch : 1.8.0
            pykdtree : 1.3.10
              pyproj : 3.6.1
             pyvista : 0.43.1
              scooby : 0.9.2
                 vtk : 9.2.6
             IPython : 8.20.0
         fastparquet : 2023.10.1
jupyter_server_proxy : 4.1.0
        nest_asyncio : 1.5.8
              pandas : 2.1.4
               trame : 3.5.1
        trame_client : 2.14.2
        trame_server : 2.15.0
           trame_vtk : 2.6.3
----------------------------------------------------------------------------------------
```
